plugins {
    id 'java'
    id 'com.github.johnrengelman.shadow' version '8.1.1'
}

group = 'burp.tdou'
version = '3.0.1'

java {
    sourceCompatibility = JavaVersion.VERSION_17
    targetCompatibility = JavaVersion.VERSION_17
}

repositories {
    mavenCentral()
}

sourceSets {
    main {
        java.srcDirs = ['extender/src/main/java']
        resources.srcDirs = ['extender/src/main/resources']
    }
}

dependencies {
    implementation 'net.portswigger.burp.extensions:montoya-api:2026.4'
    implementation 'com.google.code.gson:gson:2.10.1'
    implementation 'org.yaml:snakeyaml:2.6'
    implementation 'org.xerial:sqlite-jdbc:3.50.3.0'
    implementation 'org.apache.xmlgraphics:batik-transcoder:1.19'
    implementation 'org.apache.xmlgraphics:batik-codec:1.19'
}

tasks.withType(JavaCompile).configureEach {
    options.encoding = 'UTF-8'
}

shadowJar {
    archiveBaseName.set('FingerScan')
    archiveVersion.set("v${project.version}")
    archiveClassifier.set('')

    manifest {
        attributes(
            'Implementation-Title': 'FingerScan',
            'Implementation-Version': project.version
        )
    }
}

build.dependsOn shadowJar
