<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <groupId>burp.tdou</groupId>
    <artifactId>fingerscan</artifactId>
    <packaging>pom</packaging>
    <version>parent</version>

    <modules>
        <module>extender</module>
    </modules>

    <properties>
        <jdk.version>17</jdk.version>
        <java.version>${jdk.version}</java.version>
        <maven.compiler.source>${jdk.version}</maven.compiler.source>
        <maven.compiler.target>${jdk.version}</maven.compiler.target>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
        <montoya-api.version>2026.4</montoya-api.version>
        <gson.version>2.10.1</gson.version>
        <snakeyaml.version>2.6</snakeyaml.version>
        <sqlite-jdbc.version>3.50.3.0</sqlite-jdbc.version>
        <batik.version>1.19</batik.version>
    </properties>

    <dependencyManagement>
        <dependencies>
            <dependency>
                <groupId>net.portswigger.burp.extensions</groupId>
                <artifactId>montoya-api</artifactId>
                <version>${montoya-api.version}</version>
            </dependency>
            <dependency>
                <groupId>com.google.code.gson</groupId>
                <artifactId>gson</artifactId>
                <version>${gson.version}</version>
            </dependency>
            <dependency>
                <groupId>org.yaml</groupId>
                <artifactId>snakeyaml</artifactId>
                <version>${snakeyaml.version}</version>
            </dependency>
            <dependency>
                <groupId>org.xerial</groupId>
                <artifactId>sqlite-jdbc</artifactId>
                <version>${sqlite-jdbc.version}</version>
            </dependency>
            <dependency>
                <groupId>org.apache.xmlgraphics</groupId>
                <artifactId>batik-transcoder</artifactId>
                <version>${batik.version}</version>
            </dependency>
            <dependency>
                <groupId>org.apache.xmlgraphics</groupId>
                <artifactId>batik-codec</artifactId>
                <version>${batik.version}</version>
            </dependency>
        </dependencies>
    </dependencyManagement>


</project>