Bypass_List: ['%2f', '%2e']
Load_List:
- {loaded: true, re: springframework|reloadByURL|createJNDIRealm, method: GET, name: Spring
    Jolokia|Rce, id: 8, state: '200', type: Spring, url: /actuator/jolokia/list, info: 'Spring
    Jolokia|XXE/RCE:reloadByURL|RCE:createJNDIRealm Find!!!'}
- {loaded: true, re: api, method: GET, name: Doc File, id: 9, state: '200', type: ApiDoc,
  url: /doc.html, info: Doc File Find!!!}
- {loaded: true, re: description, method: GET, name: swagger.json, id: 10, state: '200',
  type: Spring, url: /v1/swagger.json, info: swagger.json Find!!!}
- {loaded: true, re: description, method: GET, name: swagger.json, id: 11, state: '200',
  type: Spring, url: /v2/swagger.json, info: swagger.json Find!!!}
- {loaded: true, re: swaggerVersion, method: GET, name: Swagger-resources, id: 12,
  state: '200', type: Spring, url: /swagger-resources, info: swagger-resources Find!!!}
- {loaded: true, re: SOAP|WSDL|ASP.NET|tempuri.org, method: GET, name: Soap, id: 13,
  state: '200', type: ApiDoc, url: /services, info: Soap Find!!!}
- {loaded: true, re: Web API|api, method: GET, name: Web API Help, id: 14, state: '200',
  type: ApiDoc, url: /Help, info: Web API Help Find!!!}
- {loaded: true, re: README.md, method: GET, name: README.md, id: 20, state: '206',
  type: Information leakage, url: /README.md, info: README.md Find!!!}
- {loaded: true, re: '(Swagger 2\.0)|(\"swagger\"\:)|(Swagger UI)|(\<title\>Swagger
    UI)|(swaggerVersion)|(id\=\"swagger\-ui)|swagger|openapi|apiVersion', method: GET,
  name: api-docs, id: 24, state: '200', type: ApiDoc, url: /v3/api-docs, info: api-docs
    Find !!!}
- {loaded: true, re: User-agent, method: GET, name: robots, id: 25, state: '200',
  type: Information leakage, url: /robots.txt, info: robots.txt Find !!!}
- {loaded: true, re: '(Swagger 2\.0)|(\"swagger\"\:)|(Swagger UI)|(\<title\>Swagger
    UI)|(swaggerVersion)|(id\=\"swagger\-ui)|swagger|api-docs|openapi|apiVersion',
  method: GET, name: Swagger-UI, id: 29, state: '200', type: ApiDoc, url: /api/swagger-ui.html,
  info: Swagger Find!!!}
- {loaded: true, re: Platform|Components, method: GET, name: Docker Unauthorized,
  id: 30, state: '200', type: Unauthorized, url: /version, info: Docker Unauthorized
    Find!!!}
- {loaded: true, re: repositories, method: GET, name: Docker Registry, id: 31, state: '200',
  type: Unauthorized, url: /v2/_catalog, info: Docker Registry Find!!!}
- {loaded: true, re: Jenkins, method: GET, name: Jenkins, id: 38, state: '200', type: Unauthorized,
  url: /manage, info: Jenkins Find!!!}
- {loaded: true, re: ActiveMQ, method: GET, name: ActiveMQ, id: 39, state: '200',
  type: Unauthorized, url: /admin/, info: ActiveMQ Find!!!}
- {loaded: true, re: Dashboard|Request-Handler, method: GET, name: Solr, id: 42, state: '200',
  type: Unauthorized, url: /solr/admin, info: Solr Find!!!}
- {loaded: true, re: SOAP|WSDL|ASP.NET|tempuri.org, method: GET, name: Soap, id: 44,
  state: '200', type: ApiDoc, url: /webservice, info: Soap Find!!!}
- {loaded: true, re: '(Swagger 2\.0)|(\"swagger\"\:)|(Swagger UI)|(\<title\>Swagger
    UI)|(swaggerVersion)|(id\=\"swagger\-ui)|swagger|openapi|apiVersion', method: GET,
  name: api-docs, id: 45, state: '200', type: ApiDoc, url: /api-docs, info: api-docs
    Find!!!}
- {loaded: true, re: codemirror\.addone\.fullscreen\.js, method: GET, name: Nacos,
  id: 46, state: '200', type: Unauthorized, url: /nacos/index.html, info: Nacos Find!!!}
- {loaded: true, re: (java\.runtime\.version)|(java\.class\.version)|(sping\.config\.location)|(spring\.application\.name)|(applicationConfig)|(activeProfiles)|(server\.port)|(local\.server\.port),
  method: GET, name: Spring Env RCE, id: 47, state: '200', type: Spring, url: /env,
  info: 'Actuator Env|RCE:spring.cloud.bootstrap.location|XStreamRCE:eureka.client.serviceUrl.defaultZone
    Find!!!'}
- {loaded: true, re: (java\.runtime\.version)|(java\.class\.version)|(sping\.config\.location)|(spring\.application\.name)|(applicationConfig)|(activeProfiles)|(server\.port)|(local\.server\.port)|springframework|spring.cloud.bootstrap.location|Spring
    Actuator Env RCE, method: GET, name: Spring Env RCE, id: 48, state: '200', type: Spring,
  url: /actuator/env, info: 'Actuator Env|RCE:spring.cloud.bootstrap.location|XStreamRCE:eureka.client.serviceUrl.defaultZone
    Find!!!'}
- {loaded: true, re: (src=\"\/druid\.js\")|(href\=\"\/druid\.css\"), method: GET,
  name: Druid Monitor, id: 49, state: '200', type: Unauthorized, url: /druid/index.html,
  info: Druid Monitor Find!!!}
- {loaded: true, re: '(Swagger 2\.0)|(\"swagger\"\:)|(Swagger UI)|(\<title\>Swagger
    UI)|(swaggerVersion)|(id\=\"swagger\-ui)|swagger|openapi|apiVersion', method: GET,
  name: api-docs, id: 50, state: '200', type: ApiDoc, url: /v2/api-docs, info: api-docs
    Find!!!}
- {loaded: true, re: '(Swagger 2\.0)|(\"swagger\"\:)|(Swagger UI)|(\<title\>Swagger
    UI)|(swaggerVersion)|(id\=\"swagger\-ui)|swagger|api-docs|openapi|apiVersion',
  method: GET, name: Swagger-UI, id: 51, state: '200', type: ApiDoc, url: /swagger-ui.html,
  info: Swagger-UI Find!!!}
Icon_Hash_List:
- {name: "Confluence", murmur_hash: "-305179312", md5: "", type: "Application", info: "Atlassian Confluence"}
- {name: "GitLab", murmur_hash: "-1231872293", md5: "", type: "Application", info: "GitLab CE/EE"}
- {name: "Jenkins", murmur_hash: "81586312", md5: "", type: "Application", info: "Jenkins CI"}
- {name: "Grafana", murmur_hash: "1499876150", md5: "", type: "Application", info: "Grafana Dashboard"}
- {name: "Kibana", murmur_hash: "282421062", md5: "", type: "Application", info: "Kibana Dashboard"}
- {name: "Zabbix", murmur_hash: "1196081225", md5: "", type: "Application", info: "Zabbix Monitor"}
- {name: "1panel", murmur_hash: "1300107149", md5: "", type: "Application", info: "fit2cloud 1panel"}
- {name: "1panel", murmur_hash: "1453309674", md5: "", type: "Application", info: "fit2cloud 1panel"}